[project]
name = "video-trans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "edge-tts>=7.0.2",
    "pyaudio>=0.2.14",
    "pydub>=0.25.1",
]
